### ISSUE TITLE
Aware of rstest?

### ISSUE THREAD

**Issue by msarahan** [foresterre/parameterized#32]
Hi there! thanks for your work here. I especially appreciate the IDE expansion macro. I've been using rstest (https://github.com/la10736/rstest) and really liking it. It seems a bit different from how you specify argument collections, but the same procedural macro idea. Are you aware of that project? I just wanted to make sure you are, since there may be good opportunities for mutual learning there.

**Comment by msarahan** [comment]
Am I reading your IDE macro correctly as allowing the IDE to see the parameterized test as an individual test to run, but there is no way (yet?) to run an individual case within that parameterized test?

I'm hopeful that there is a way to re-run just one specific failing case from a parameterized test, but I haven't found a good way yet.

**Comment by foresterre** [comment]
Hi :wave: ! 
<sub>I wrote a bit more than originally intended</sub>


### Origin

I started this project for two reasons: Primarily because I got annoyed by writing individual `#[test]` cases for my [sic](https://github.com/foresterre/sic) project, where cases where very similar. In my Java projects I often used `@ParameterizedTest` from `JUnit`, but after trying a few search terms on `crates.io`, I couldn't find something for parameterized testing. I probably should have taken a better look because, as I discovered later, `rstest` did exist at that point. I'm however not disappointed that I didn't, because (for the second reason) I also thought it could be nice learning opportunity: to learn how  procedural macros are written. I had used them often in my regular Rust code, but until that moment never really looked into how they worked :smile:.

I guess the disadvantage of having also written your own crate is that you become a bit attached to it (that's one reason for me to keep using it :sweat_smile:). 

I'm also still not yet sure what syntax I would like for any parameterized macro. For example, the syntax for [parameterized](https://github.com/foresterre/parameterized) was inspired by `@ParameterizedTest` which I used regularly, and puts focus on input values over test cases (e.g. for an argument of  a test function, different inputs are close together):

**[parameterized](https://github.com/foresterre/parameterized) usage**

```rust
#[parameterized(input = {
    -2, // here specific values for an argument are in close vicinity of each other
    -1,
    0,
    1,
    2
}, output = {
    4, // ... but this has a disadvantage when you have a lot of cases, and want to compare arguments, e.g. because a certain case fails  
    1,
    0,
    1,
    4
})]
fn test_squared(input: i8, output: i8) {
    assert_eq(squared(input), output);
}
```

I recently created a second parameterized crate called [sif](https://github.com/foresterre/sif)  where the syntax is more focused towards individual test cases, as I saw just now is probably more similar to how `rstest` does it (but still slightly different):


**[sif](https://github.com/foresterre/sif) usage**

```rust
#[parameterized]
#[case(-2, 4)]
#[case(-1, 1)]
#[case( 0, 0)]
#[case( 1, 1)]
#[case( 2, 4)]
fn test_squared(input: i8, output: i8) {
    assert_eq(squared(input), output);
}
```

Looking at `rstest`, I think the authors did a great job at providing flexible options for about every possible use-case. My crate is much more bare-bones and simple in that regard ☺️.


### The ide! macro
Regarding this macro, it is a way to trick the IDE by stating "this module contains test cases"  and simply generates an empty test case. When the IDE detects the generated empty test case with the regular  `#[test]` attribute, it marks the outer module as containing runnable tests:

![image](https://user-images.githubusercontent.com/5955761/88639856-8828e800-d0bd-11ea-9938-48e9c68e98b1.png)

**ide! macro definition**

```
#[macro_export]
macro_rules! ide {
    () => {
        #[test]
        fn __mark_with_test_intent() {}
    };
}
```

The idea here is to have a separately runnable module for every defined test, but this indeed does not help when running individual (failing) cases. If you find a way to to that in the IDE (be it vscode or intellij-rust, or something else), I would be grateful to learn how; perhaps we can learn from it =). Or perhaps I should bite the bullet and have an attempt at improving this in intellij-rust myself... 

If you don't mind using the command line, then you can use ` cargo test --  "<test case>"`, for example in this repo you could run: ` cargo test --  "tests::readme_test::test_add5::case_0"` (_it does require some knowledge on the generated test case name_, however that should be evident from the failed test output)

I hoped that with the new declarative macro expansion engine of intellij-rust, it would be possible to at least reduce some of the boilerplate around defining a test case: `mod much_boilerplate { use super::*; ide!(); ... actual test fn ...  }`, however that doesn't  [seem](https://github.com/foresterre/parameterized/blob/proto_decl_testmod/src/lib.rs#L46) to work:

![image](https://user-images.githubusercontent.com/5955761/88641354-5dd82a00-d0bf-11ea-99b8-a7e5bc09a5af.png)



### Thanks!

Thanks for your suggestion and questions!
